/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/blackhole.glb 
Author: shikoooooooo (https://sketchfab.com/shikoooooooo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blackhole-32f978d0e7354af293fa498f2998b14c
Title: Blackhole
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/blackhole.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Blackhole" scale={0.01}>
          <group name="Lathe_S" position={[0, 12.893, 0]} rotation={[0, -0.955, 0]}>
            <mesh name="Lathe_S_Blackhole_01_0" geometry={nodes.Lathe_S_Blackhole_01_0.geometry} material={materials.Blackhole_01} position={[0, -39.874, 0]} scale={267.68} />
          </group>
          <group name="Lathe_M" position={[0, 5.518, 0]} rotation={[0, -0.478, 0]}>
            <mesh name="Lathe_M_Blackhole_02_0" geometry={nodes.Lathe_M_Blackhole_02_0.geometry} material={materials.Blackhole_01} position={[0, -39.874, 0]} scale={364.438} />
          </group>
          <group name="Lathe_L" rotation={[0, -0.318, 0]}>
            <mesh name="Lathe_L_Blackhole_03_0" geometry={nodes.Lathe_L_Blackhole_03_0.geometry} material={materials.Blackhole_03} position={[0, -152.901, 0]} scale={550.023} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/blackhole.glb')
