/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spaceship.glb 
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rusty-spaceship-orange-18541ebed6ce44a9923f9b8dc30d87f5
Title: Rusty Spaceship - Orange
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/spaceship.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[7.393, -0.431, 3.427]} scale={9.467} />
      <mesh geometry={nodes.Cube005_cockpit_0.geometry} material={materials.cockpit} position={[7.408, 1.297, 2.87]} rotation={[0.087, 0, 0]} scale={1.799} />
    </group>
  )
}

useGLTF.preload('/spaceship.glb')
